# default settings for pan interviews
# note that a number sign (#) functions as a comment, so use in strings requires quotation marks

device_name: 'Tablet PC #1'
interviewer_name: John
location: Machiguenga Communities
latitude:
longitude:
responses_directory: ./responses
responses_directory_backup: ./sdcard-test
shiny_ui_theme: slate
